services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  publisher:
    build: .
    command: python backend/publisher.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DAYS_BACK=14
      - HISTORY_PATH=/app/data/History.db
    volumes:
      - ./data/History.db:/app/data/History.db:ro
      - ./data:/app/data

  worker:
    build: .
    command: python backend/worker.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 2